stages:
  train:
    cmd: python model/train.py
    deps:
      - model/train.py
      - data/creditcard.csv
    outs:
      - model/fraud_model.pkl
      - model/scaler.pkl
      - model/reference_sample.parquet
      - model/shap_summary.png
    metrics:
      - model/metadata.json:
          cache: false